=== StockExtremeBros/xml-lab/data/timetable.dtd
<?xml version='1.0' encoding='UTF-8'?>


<!ELEMENT courses (courseslot)*>
<!ELEMENT timeslots (timeslot)*>

<!ELEMENT courseslot (booking)*>
<!ELEMENT timeslot (booking)*>
<!ATTLIST courseslot
    code CDATA #IMPLIED
  >
<!ATTLIST timeslot
    start CDATA #IMPLIED
    end CDATA #IMPLIED
  >

<!ELEMENT booking (day|code|start|end|building|room|type|instructor)*>
<!ELEMENT days (dayslot)*>

<!ELEMENT dayslot (booking)*>
<!ATTLIST dayslot
    day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!ELEMENT day (#PCDATA)>

<!ELEMENT start (#PCDATA)>

<!ELEMENT end (#PCDATA)>

<!ELEMENT building (#PCDATA)>

<!ELEMENT room (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT instructor (#PCDATA)>

<!ELEMENT code (#PCDATA)>

=== StockExtremeBros/xml-lab/data/timeslots.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE timeslots SYSTEM 'timetable.dtd'>

<timeslots>
    <timeslot start="0830" end="1020">
        <booking>
            <day>Friday</day>
            <code>BLAW3600</code>
            <type>lecture</type>
            <building>SW5</building>
            <room>1840</room>
            <instructor>Catherine Ryan</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="0930" end="1120">
        <booking>
            <day>Monday</day>
            <code>COMP4985</code>
            <type>lecture/lab</type>
            <building>SE12</building>
            <room>323</room>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <day>Tuesday</day>
            <code>COMP4981</code>
            <type>lecture/lab</type>
            <building>SE12</building>
            <room>323</room>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <day>Thursday</day>
            <code>COMP4981</code>
            <type>lecture/lab</type>
            <building>SE12</building>
            <room>323</room>
            <instructor>Aman Abdulla</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="0930" end="1220">
        <booking>
            <day>Wednesday</day>
            <code>COMP4985</code>
            <type>lecture/lab</type>
            <building>SE12</building>
            <room>323</room>
            <instructor>Aman Abdulla</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="1130" end="1220">
        <booking>
            <day>Monday</day>
            <code>COMP4735</code>
            <type>lecture</type>
            <building>SW1</building>
            <room>1205</room>
            <instructor>Mirela Gutica</instructor>
        </booking>
        <booking>
            <day>Tuesday</day>
            <code>COMP4560</code>
            <type>lecture</type>
            <building>SW5</building>
            <room>1850</room>
            <instructor>Brenda Fine</instructor>
        </booking>
        <booking>
            <day>Monday</day>
            <code>COMP4735</code>
            <type>lecture</type>
            <building>SW3</building>
            <room>1710</room>
            <instructor>Mirela Gutica</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="1230" end="1320">
        <booking>
            <day>Wednesday</day>
            <code>COMP4985</code>
            <type>lecture/lab</type>
            <building>SE12</building>
            <room>323</room>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <day>Friday</day>
            <code>COMP4560</code>
            <type>lecture</type>
            <building>SW3</building>
            <room>1750</room>
            <instructor>Brenda Fine</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="1230" end="1320">
        <booking>
            <day>Monday</day>
            <code>BLAW3600</code>
            <type>lab</type>
            <building>SW9</building>
            <room>127</room>
            <instructor>Catherine Ryan</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="1330" end="1420">
        <booking>
            <day>Wednesday</day>
            <code>COMP4735</code>
            <type>lecture</type>
            <building>SW1</building>
            <room>1205</room>
            <instructor>Mirela Gutica</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="1430" end="1520">
        <booking>
            <day>Tuesday</day>
            <code>COMP4711</code>
            <type>lecture</type>
            <building>SW5</building>
            <room>1840</room>
            <instructor>Jim Parry</instructor>
        </booking>
    </timeslot>
    
    <timeslot start="1530" end="1720">
        <booking>
            <day>Monday</day>
            <code>COMP4560</code>
            <type>lab</type>
            <building>SE12</building>
            <room>320</room>
            <instructor>Brenda Fine</instructor>
        </booking>
        <booking>
            <day>Tuesday</day>
            <code>COMP4711</code>
            <type>lab</type>
            <building>SE12</building>
            <room>321</room>
            <instructor>Jim Parry</instructor>
        </booking>
        <booking>
            <day>Thursday</day>
            <code>COMP4735</code>
            <type>lab</type>
            <building>SE12</building>
            <room>322</room>
            <instructor>Matthew Linder</instructor>
        </booking>
    </timeslot>
    
</timeslots>

=== StockExtremeBros/xml-lab/data/days.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE days SYSTEM 'timetable.dtd'>

<days>
    <dayslot day="Monday">
        <booking>
            <code>COMP4985</code>
            <start>0930</start> 
            <end>1120</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <code>COMP4735</code>
            <start>1130</start> 
            <end>1220</end>
            <building>SW1</building>
            <room>1205</room>
            <type>lecture</type>
            <instructor>Mirela Gutica</instructor>
        </booking>
        <booking>
            <code>BLAW3600</code>
            <start>1230</start> 
            <end>1420</end>
            <building>SW9</building>
            <room>127</room>
            <type>lab</type>
            <instructor>Catherine Ryan</instructor>
        </booking>
        <booking>
            <code>COMP4560</code>
            <start>1530</start> 
            <end>1720</end>
            <building>SE12</building>
            <room>320</room>
            <type>lab</type>
            <instructor>Brenda Fine</instructor>
        </booking>
    </dayslot>
    
    <dayslot day="Tuesday">
        <booking>
            <code>COMP4981</code>
            <start>0930</start> 
            <end>1120</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <code>COMP4560</code>
            <start>1130</start> 
            <end>1220</end>
            <building>SW5</building>
            <room>1850</room>
            <type>lecture</type>
            <instructor>Brenda Fine</instructor>
        </booking>
        <booking>
            <code>COMP4711</code>
            <start>1430</start>
            <end>1520</end>
            <building>SW5</building>
            <room>1840</room>
            <type>lecture</type>
            <instructor>Jim Parry</instructor>
        </booking>
        <booking>
            <code>COMP4711</code>
            <start>1530</start>
            <end>1720</end>
            <building>SE12</building>
            <room>321</room>
            <instructor>Jim Parry</instructor>
        </booking>
    </dayslot>
    
    <dayslot day="Wednesday">
        <booking>
            <code>COMP4985</code>
            <start>0930</start> 
            <end>1220</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <code>COMP4981</code>
            <start>1230</start> 
            <end>1320</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <code>COMP4735</code>
            <start>1330</start>
            <end>1420</end>
            <building>SW1</building>
            <room>1205</room>
            <type>lecture</type>
            <instructor>Mirela Gutica</instructor>
        </booking>
    </dayslot>
    
    <dayslot day="Thursday">
        <booking>
            <code>COMP4981</code>
            <start>0930</start> 
            <end>1120</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <code>COMP4735</code>
            <start>1130</start>
            <end>1220</end>
            <building>SW1</building>
            <room>1710</room>
            <type>lecture</type>
            <instructor>Mirela Gutica</instructor>
        </booking>
        <booking>
            <code>COMP4735</code>
            <start>1530</start>
            <end>1720</end>
            <building>SE12</building>
            <room>322</room>
            <type>lab</type>
            <instructor>Matthew Linder</instructor>
        </booking>
    </dayslot>
    
    <dayslot day="Friday">
        <booking>
            <code>BLAW3600</code>
            <start>0830</start> 
            <end>1020</end>
            <building>SW5</building>
            <room>1840</room>
            <type>lecture</type>
            <instructor>Catherine Ryan</instructor>
        </booking>
        <booking>
            <code>COMP4560</code>
            <start>1230</start> 
            <end>1320</end>
            <building>SW3</building>
            <room>1750</room>
            <type>lecture</type>
            <instructor>Brenda Fine</instructor>
        </booking>
    </dayslot>
    
</days>

=== StockExtremeBros/xml-lab/data/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE courses SYSTEM 'timetable.dtd'>
<courses>
    <courseslot code="COMP4711">
        <booking>
            <day>Tuesday</day>
            <start>1430</start>
            <end>1520</end>
            <building>SW5</building>
            <room>1840</room>
            <type>lecture</type>
            <instructor>Jim Parry</instructor>
        </booking>
        <booking>
            <day>Tuesday</day>
            <start>1530</start>
            <end>1720</end>
            <building>SE12</building>
            <room>321</room>
            <instructor>Jim Parry</instructor>
        </booking>
    </courseslot>
    <courseslot code="COMP4735">
        <booking>
            <day>Monday</day>
            <start>1130</start> 
            <end>1220</end>
            <building>SW1</building>
            <room>1205</room>
            <type>lecture</type>
            <instructor>Mirela Gutica</instructor>
        </booking>
        <booking>
            <day>Wednesday</day>
            <start>1330</start>
            <end>1420</end>
            <building>SW1</building>
            <room>1205</room>
            <type>lecture</type>
            <instructor>Mirela Gutica</instructor>
        </booking>
        <booking>
            <day>Thursday</day>
            <start>1130</start>
            <end>1220</end>
            <building>SW1</building>
            <room>1710</room>
            <type>lecture</type>
            <instructor>Mirela Gutica</instructor>
        </booking>
        <booking>
            <day>Thursday</day>
            <start>1530</start>
            <end>1720</end>
            <building>SE12</building>
            <room>322</room>
            <type>lab</type>
            <instructor>Matthew Linder</instructor>
        </booking>
    </courseslot>
    <courseslot code="COMP4985">
        <booking>
            <day>Monday</day>
            <start>0930</start> 
            <end>1120</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <day>Wednesday</day>
            <start>0930</start> 
            <end>1220</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
    </courseslot>
    <courseslot code="COMP4981">
        <booking>
            <day>Tuesday</day>
            <start>0930</start> 
            <end>1120</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <day>Thursday</day>
            <start>0930</start> 
            <end>1120</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
        <booking>
            <day>Wednesday</day>
            <start>1230</start> 
            <end>1320</end>
            <building>SE12</building>
            <room>323</room>
            <type>lecture/lab</type>
            <instructor>Aman Abdulla</instructor>
        </booking>
    </courseslot>
    <courseslot code="COMP4560">
        <booking>
            <day>Monday</day>
            <start>1530</start> 
            <end>1720</end>
            <building>SE12</building>
            <room>320</room>
            <type>lab</type>
            <instructor>Brenda Fine</instructor>
        </booking>
        <booking>
            <day>Tuesday</day>
            <start>1130</start> 
            <end>1220</end>
            <building>SW5</building>
            <room>1850</room>
            <type>lecture</type>
            <instructor>Brenda Fine</instructor>
        </booking>
        <booking>
            <day>Friday</day>
            <start>1230</start> 
            <end>1320</end>
            <building>SW3</building>
            <room>1750</room>
            <type>lecture</type>
            <instructor>Brenda Fine</instructor>
        </booking>
    </courseslot>
    <courseslot code="BLAW3600">
        <booking>
            <day>Monday</day>
            <start>1230</start> 
            <end>1420</end>
            <building>SW9</building>
            <room>127</room>
            <type>lab</type>
            <instructor>Catherine Ryan</instructor>
        </booking>
        <booking>
            <day>Friday</day>
            <start>0830</start> 
            <end>1020</end>
            <building>SW5</building>
            <room>1840</room>
            <type>lecture</type>
            <instructor>Catherine Ryan</instructor>
        </booking>
    </courseslot>
</courses>
